---
experiment:
  pipeline: Pooled Cell Painting
  project_tag: Periscope
  batches:
    - 20210124_6W_CP228
  plates:
    - CP228A
    - CP228B
  wells:
    well1:
      - Well1
    well2:
      - Well2
    well3:
      - Well3
    well4:
      - Well4
    well5:
      - Well5
    well6:
      - Well6
  split:
    qc:
      batches: true
      plates: true
      wells: true
    profile:
      batches: true
      plates: false
      wells: true
  barcoding_cycles: 10
  sites_per_image_grid_side: 10
  control_barcode_ids:
    - Chr2
---
directory_structure:
  input_data_dir: /home/ubuntu/bucket/projects/2018_11_20_Periscope_Calico/workspace/analysis
  batch_id_folder: true
  output_data_dir: data/
  preprocess:
    base: 0.site-qc/
    batch_id_folder: true
    spots: spots/
    paint: paint/
    data: data/
    results: results/
    figures: figures/
  profile:
    base: 1.profiles/
    batch_id_folder: true
    single_cell: single_cell/
    profiles: profiles/
